
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Inside Docker network, Prometheus is reachable by container name
    url: http://prometheus:9090
    isDefault: true
    editable: false